### ISSUE TITLE
kwayland install error

### ISSUE THREAD

**Issue by oldradio77** [tsaop/crux-kf5#5]
qtwayland modules needed
Build qtwayland from https://wiki.qt.io/QtWayland fails
Help build kwayland, how obtain qtwayland modules?
Thanks!

**Comment by TimB87** [comment]
Hi,
qtwayland should be build with opt/qt5 automagically when you have wayland around. It might need mesa3d to be compiled with wayland support as well, not sure about that. Let us know how it goes!

edit: to be clear, i would suggest that
`prt-get depinst wayland-protocols && prt-get update -fr qt5`
If that works for you, fine, if not, you need to enable wayland in mesa3d, you can look at my Pkgfile here: https://github.com/TimB87/crux-wayland/blob/master/mesa3d/Pkgfile

**Comment by oldradio77** [comment]
Thank! I rebuid qt5 and qtwayland  libs now there! kwayland successfully installed. Then problem to build signon-plugin-oauth2, I think here in this thread is an offtopic

**Comment by tsaop** [comment]
Ideally wayland-protocols should be added to qt5 dependencies.

**Comment by TimB87** [comment]
wayland is currently not really supported in CRUX, and since it's purely optional people generally struggle to accept added dependencies to their systems.

I would be happy if we can get optional support for wayland like my little crux-wayland overlay tries to do it, ideally I would want the possibility to build a pure wayland desktop over adding all the dependencies for all the use-cases out there tbh

Anyway: in your case I'd say create a README for users to ignore that tells them what to do to get it running.

**Comment by tsaop** [comment]
Sounds reasonable.

I have added a README to kwayland, see the below commit:
https://github.com/tsaop/crux-kf5/commit/9f61bfa54c81922167f56b40282175452b49cb19

Let me know if you have other suggestions.

Thanks.

**Comment by TimB87** [comment]
I would want to note that I am not actively maintaining that repo, it's just a showcase because i proposed it on IRC some other day, also there might more be needed to actually run a successful wayland session that I missed to post/to mention.

Also: maybe you want to give your users the command that will take of the situation for them, like shown in my first comment. Otherwise, good stuff :)

**Comment by tsaop** [comment]
I reworded the README as per your suggestions; should be more clear now.

As for the full wayland session, it's very likely that I need to modify some other ports, but I haven't attempted to do so.

@oldradio77 
I have fixed build for signon-plugin-oauth2, please try it and open a separate issue if you have other problems.
